### ISSUE TITLE
Question about proj_first argument regarding attentive fusion and v2vnet fusion

### ISSUE THREAD

**Issue by dttsak** [DerrickXuNu/OpenCOOD#49]
Hi! I have a question for the intermediate fusion. I understand that the point_pillar_intermediate_fusion.yaml refers to the attentive fusion mechanism which requires the point cloouds of all cavs to be projected to the ego's coordinates system before the backbone layer, but the aforementioned yaml file does not include the proj_first argument in the fusion args. On the other hand the proj_first argument is included in  the point_pillar_v2vfusion.yaml which from my understanding should project the feature maps to the ego's coordinate system at the fusion step using the pairwise_t_matrix. I am very confused any help would be greatly appreciated. Thanks for the great work!

**Comment by DerrickXuNu** [comment]
Hi, thanks for using Opencood. By default, if there is no proj_first flag in the yaml, it will be set to true automatically. That's why you didn't see it in the intermediate fusion. For the V2VNet, when you set the proj_first to False, it will be exactly the same as the original paper. I set it to true to make it consistent with other methods to have a fair comparison on the fusion algorithm.

**Comment by DerrickXuNu** [comment]
Because it is much faster and occupies less computational source, which is crucial for this application.
