### ISSUE TITLE
something wrong with the open3D

### ISSUE THREAD

**Issue by Yue2000** [DerrickXuNu/OpenCOOD#83]
现在show_vis或者save_vis时，open3D库会出现一些问题无法运行

**Comment by Yue2000** [comment]
![1~))D~I L0HF9$~%@LO AN8](https://github.com/DerrickXuNu/OpenCOOD/assets/129492130/0030a779-c2b8-4263-9b61-b1493f156c47)

**Comment by DerrickXuNu** [comment]
Thanks for using OpenCOOD! This is error is not caused by Open3D. It happens when you have no predictions but try to draw prediction bounding box, which gives you a "nonetype" object error. I will fix it later, but for now, can you just write a if condition to check if the object is none, and skip the bbx visualization if it is?

**Comment by Yue2000** [comment]
Thanks for replying! I can get the results without visualizing, but there is a problem visualizing and saving the visualization results.

**Comment by DerrickXuNu** [comment]
Yes, this what I am saying. The code can deal with Nonetype predictions without visualization. But when it comes with visualization, this will give an error
