### ISSUE TITLE
LiDAR config for OPV2V replay

### ISSUE THREAD

**Issue by xavhl** [DerrickXuNu/OpenCOOD#92]
The [official website](https://mobility-lab.seas.ucla.edu/opv2v/) did state that the vertical fov is 26.8 degrees. But may you kindly provide more details on the sensor config parameters? E.g. upper and lower fov for LiDAR sensor. 

On other hand, a set of four RGB cameras are installed on the vehicle (respectively on front, right, left and back). How about for the LiDAR sensors? 

Thank you!

**Comment by DerrickXuNu** [comment]
OPV2V actually contains yaml files with LiDAR configuration details. Please check data_protocol.yaml under each scenario

**Comment by xavhl** [comment]
Thank you for the information!

**Comment by eyabesbes** [comment]
> The [official website](https://mobility-lab.seas.ucla.edu/opv2v/) did state that the vertical fov is 26.8 degrees. But may you kindly provide more details on the sensor config parameters? E.g. upper and lower fov for LiDAR sensor.
> 
> On other hand, a set of four RGB cameras are installed on the vehicle (respectively on front, right, left and back). How about for the LiDAR sensors?
> 
> Thank you!

Hi,

I noticed you've been working on replaying Opv2VScenes with the Lidar sensor. Since you seem knowledgeable about this, could you assist me with replaying the LiDAR data using logreplay? I'm currently working on this task and I would appreciate any guidance you can provide regarding replaying the LiDAR data.

Thank you!
